INSERT INTO [ticket]
           ([firstname]
           ,[lastname]
           ,[company]
           ,[address1]
           ,[address2]
           ,[town]
           ,[district]
           ,[country]
           ,[postcode]
           ,[email]
           ,[phone]
           ,[fax]
           ,[alternate]
           ,[alternate_name]
           ,[alternate_email]
           ,[alternate_phone]
           ,[product]
           ,[trouble]
           ,[report]
           ,[shortdesc]
           ,[fulldesc]
           ,[status]
           ,[contract]
           ,[timesubmitted]
           ,[level]
           ,[viewedby]
           ,[timeviewed]
           ,[user_id]
           ,[timeclosed]
           ,[userdetails]
           ,[pin]
           ,[emergency]
           ,[ticket_file]
           ,[ticket_file2]
           ,[ticket_file3]
           ,[oemuser]
           ,[timelastaction]
           ,[serialNo]
           ,[qi]
           ,[email1_sent]
           ,[email2_sent]
           ,[observeremail]
           ,[observerstate]
           ,[CRnum]
           ,[CRurl]
           ,[QInum]
           ,[QIurl]
           ,[INTnum]
           ,[INTurl]
           ,[SPTnum]
           ,[SPTurl]
           ,[EXTnum]
           ,[EXTurl]
           ,[severity]
           ,[customemotion]
           ,[cust_coop]
           ,[current_support_level]
           ,[RaisedByOEMReseller]
           ,[OEM_reseller_userID]
           ,[EscalationHML]
           ,[LastEscalationTime]
           ,[SendToJira]
           ,[EscalationSeverity]
           ,[EscalationPriority])
     VALUES
           ('BlueArc'
           ,'Support'
           ,385
           ,''
           ,''
           ,'San Jose'
           ,'CA'
           ,'United States'
           ,''
           ,'support@bluearc.com'
           ,'866-864-1090'
           ,''
           ,NULL
           ,''
           ,''
           ,''
           ,'F5404E'
           ,'Drive Issue'
           ,'General Information'
           ,'Parity retry failed on array 03: Ref Bluearc case:00047704'
           ,'Parity check flagged the following errors,   implicating multiple disks, please advise on   next course of action.    Regards    Rob              Mon Mar 28 2011 08:10:18 Array 03 Parity   Retry  Failed 0 Errors Drive = 4 Chunk   address = 405cfa00  Mon Mar 28 2011 08:10:44 Array 03 Parity   Retry  Failed 1 Errors Drive = 5 Chunk   address = 405e1280  Mon Mar 28 2011 08:10:44 Array 03 Parity   Retry  Failed 2 Errors Drive = 0 Chunk   address = 405e1380  Mon Mar 28 2011 13:57:59 Array 03 Parity   Retry  Failed 2 Errors Drive = 4 Chunk   address = 4877b600  Tue Mar 29 2011 04:15:36 Array 03 Parity   Retry  Failed 2 Errors Drive = 7 Chunk   address = 581e6700'
           ,'C'
           ,'No'
           ,'2011-03-30 03:57:45.000'
           ,'N'
           ,79
           ,'2011-04-20 11:45:15.000'
           ,79
           ,NULL
           ,NULL
           ,2369
           ,'No'
           ,'4867-techsupportdb.zip'
           ,NULL
           ,NULL
           ,2965
           ,'2011-04-18 08:55:44.000'
           ,''
           ,NULL
           ,0
           ,0
           ,NULL
           ,NULL
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,NULL
           ,NULL
           ,2
           ,''
           ,''
           ,'H'
           ,'2011-11-11 00:00:00'
           ,NULL
           ,NULL
           ,NULL);

INSERT INTO [ticket]
           ([firstname]
           ,[lastname]
           ,[company]
           ,[address1]
           ,[address2]
           ,[town]
           ,[district]
           ,[country]
           ,[postcode]
           ,[email]
           ,[phone]
           ,[fax]
           ,[alternate]
           ,[alternate_name]
           ,[alternate_email]
           ,[alternate_phone]
           ,[product]
           ,[trouble]
           ,[report]
           ,[shortdesc]
           ,[fulldesc]
           ,[status]
           ,[contract]
           ,[timesubmitted]
           ,[level]
           ,[viewedby]
           ,[timeviewed]
           ,[user_id]
           ,[timeclosed]
           ,[userdetails]
           ,[pin]
           ,[emergency]
           ,[ticket_file]
           ,[ticket_file2]
           ,[ticket_file3]
           ,[oemuser]
           ,[timelastaction]
           ,[serialNo]
           ,[qi]
           ,[email1_sent]
           ,[email2_sent]
           ,[observeremail]
           ,[observerstate]
           ,[CRnum]
           ,[CRurl]
           ,[QInum]
           ,[QIurl]
           ,[INTnum]
           ,[INTurl]
           ,[SPTnum]
           ,[SPTurl]
           ,[EXTnum]
           ,[EXTurl]
           ,[severity]
           ,[customemotion]
           ,[cust_coop]
           ,[current_support_level]
           ,[RaisedByOEMReseller]
           ,[OEM_reseller_userID]
           ,[EscalationHML]
           ,[LastEscalationTime]
           ,[SendToJira]
           ,[EscalationSeverity]
           ,[EscalationPriority])
     VALUES
           ('Gerardo'
           ,'Ramos'
           ,417
           ,''
           ,''
           ,''
           ,'Dayton'
           ,'United States'
           ,''
           ,'GRamos@curtisswright.com'
           ,''
           ,''
           ,NULL
           ,''
           ,''
           ,''
           ,'F6500'
           ,'Other'
           ,'Software Issue'
           ,'Missing CD'
           ,'Did not find the ISO image in the FTP site. Is this available at this time?'
           ,'C'
           ,'No'
           ,'2011-03-30 09:45:28.000'
           ,'N'
           ,79
           ,'2011-04-05 19:58:20.000'
           ,79
           ,NULL
           ,NULL
           ,4965
           ,'No'
           ,NULL
           ,NULL
           ,NULL
           ,3669
           ,'2011-04-01 16:10:20.000'
           ,''
           ,NULL
           ,0
           ,0
           ,NULL
           ,NULL
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,NULL
           ,NULL
           ,2
           ,''
           ,''
           ,'H'
           ,'2011-11-11 00:00:00'
           ,NULL
           ,NULL
           ,NULL);
